{
 "title": "BIG-IP System Dashboard",
 "tags": [ "bigip" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Current CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "stats.gauges.f5telemetry.*.system.cpu"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "telemetryEventCategory:LTM",
     "timeField": "data.event_timestamp"
    }
   ]
  },
  {
   "title": "Juice Shop VS Current Conns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.f5telemetry.*.virtualServers.-JuiceShop-Application_1-serviceMain.clientside-curConns"
    }
   ]
  },
  {
   "title": "Violations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "telemetryEventCategory:ASM",
     "timeField": "data.date_time"
    }
   ]
  },
  {
   "title": "Violation Locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data.geo_location",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "data.date_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "data.geo_location",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "telemetryEventCategory:ASM",
     "timeField": "data.date_time"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "5xx Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "stats.gauges.f5telemetry.*.httpProfiles.-Common-http.5xxResp"
    }
   ]
  },
  {
   "title": "2xx Responses",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(stats.gauges.f5telemetry.*.httpProfiles.-Common-http.2xxResp)"
    }
   ]
  },
  {
   "title": "3xx Responses",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(stats.gauges.f5telemetry.*.httpProfiles.-Common-http.3xxResp)"
    }
   ]
  },
  {
   "title": "4xx Responses",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(stats.gauges.f5telemetry.*.httpProfiles.-Common-http.4xxResp)"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(stats.gauges.f5telemetry.*.virtualServers.-JuiceShop-Application_1-serviceMain.clientside-bitsOut), 3)"
    }
   ]
  },
  {
   "title": "Connections Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(stats.gauges.f5telemetry.*.virtualServers.-JuiceShop-Application_1-serviceMain.clientside-curConns), 3)"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.f5telemetry.*.system.cpu)"
    },
    {
     "target": "aliasByMetric(stats.gauges.f5telemetry.*.system.tmmCpu)"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.f5telemetry.*.system.memory)"
    },
    {
     "target": "aliasByMetric(stats.gauges.f5telemetry.*.system.tmmMemory)"
    }
   ]
  }
 ]
}