---

- name: Set DO release url
  set_fact:
    package_release_url: "{{ f5_networks_github_base_url }}/f5-declarative-onboarding/releases/{{ 'latest' if do_use_latest == true else 'tags/' + do_requested_tag }}"

- name: Get specific or latest DO version and checksum file download urls
  uri:
    url: "{{ package_release_url }}"
    return_content: true
    status_code: 200
  register: do_github_releases
  check_mode: false

- set_fact:
    # weird workaround below: https://github.com/ansible/ansible/issues/27299
    do_release_url: "{{ do_github_releases.json | to_json | from_json | json_query('assets[?ends_with(name, `.rpm`)] | [0] | browser_download_url') }}"
    do_release_checksum_url: "{{ do_github_releases.json | to_json | from_json | json_query('assets[?ends_with(name, `.sha256`)] | [0] | browser_download_url') }}"

- debug:
    var: do_release_url
    verbosity: 2

- name: Download DO checksum file (sha256)
  get_url:
    url: "{{ do_release_checksum_url }}"
    dest: "{{ tmp_dir }}/{{ do_file_sha256 }}"
    force: true
  check_mode: false

- name: Set DO checksum var
  set_fact:
    do_checksum: "{{ lookup('file', '{{ tmp_dir }}/{{ do_file_sha256 }}') | regex_search('^(\\S*)') }}"

- name: Download DO RPM file with check (sha256)
  get_url:
    url: "{{ do_release_url }}"
    dest: "{{ tmp_dir }}/{{ do_file }}"
    checksum: "sha256:{{ do_checksum }}"
    force: true
  check_mode: false


- name: Add an iAppLX Package for Declarative Onboarding
  bigip_lx_package:
    package: "{{ tmp_dir }}/{{ do_file }}"
    provider: "{{ bigip_provider }}"
    state: present
  delegate_to: localhost
