version: '3'
services:
  grafana:
    image: grafana/grafana:6.4.3
    restart: unless-stopped
    depends_on:
      - graphite
      - elasticsearch
    ports:
      - "3030:3000"
    # leave the following boolean env vars quoted. Known issue: https://github.com/docker/compose/issues/1788
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_AUTO_ASSIGN_ORG: "true"
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: Editor
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: X-WEBAUTH-USER
      GF_AUTH_PROXY_HEADER_PROPERTY: username
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_WHITELIST: 10.0.3.0/24
      GF_INSTALL_PLUGINS: grafana-worldmap-panel
      GF_SERVER_ROOT_URL: http://grafana.server.name:3030

  graphite:
    image: "graphiteapp/graphite-statsd:1.1.5-13"
    restart: unless-stopped
    ports:
      - "3400:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
      - "8080:8080"

  elasticsearch:
    image: "elasticsearch:7.3.1"
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  juice_shop_app:
    image: bkimminich/juice-shop:v8.7.0
    restart: unless-stopped
    ports:
      - "3300:3000"
