---
- name: Start docker service
  service:
    name: docker
    state: started
    enabled: true
  register: docker_service_output
  become: true
  ignore_errors: true

- name: Ensure that docker has started...
  shell: docker ps
  register: docker_status
  until: docker_status.rc == 0
  failed_when: docker_status.rc == 1
  retries: 4
  delay: 5
  tags:
    - check-docker-service

- debug:
    var: docker_status
  tags:
    - check-docker-service

- debug:
    msg: role path is  {{ role_path }} 

- name: copy docker-compose to docker host                                         
  copy:
    src: "{{ role_path }}/files/docker/docker-compose.yml"
    dest: ~/docker-compose.yml

- name: Tear down existing services
  docker_compose:
    project_src: "~/"
    state: absent

- name: Create and start services
  docker_compose:
    project_src: "~/"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "{{ inventory_hostname }}"
  register: output
